name: XpBottles
main: me.codedred.xpbottles.Main
authors: [CodedRed, Cmaaxx]
version: 1.4.0
api-version: 1.13
softdepend: [Vault]

commands:
  exp:
    description: Allows you to withdraw exp into an exp bottle!
    usage: /exp
  xp:
    description: Allows you to use admin exp commands!
    usage: /xp

  